# Generated by Django 5.0.4 on 2024-04-21 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='my_invite_code',
            new_name='invite_code',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='entered_invite_code',
            new_name='invited_by',
        ),
    ]
